### ISSUE TITLE
Syncing up with recent changes in next.jdbc

### ISSUE THREAD

**Issue by seancorfield** [metosin/porsas#11]
This is mostly a heads up that `next.jdbc` row builders have a couple of extra expectations compared to when you first created `porsas`. Illustrated by the updated record-based builder in the test suite here: https://github.com/seancorfield/next-jdbc/blob/develop/test/next/jdbc/result_set_test.clj#L380-L406

The two main points:

* There was an implicit assumption that all builders would support `:cols` and `:rsmeta` to return the vector of column names and the `ResultSetMetaData` but that has been made explicit and all the built-in builders now explicitly support `clojure.lang.ILookup` for those keys,
* A new, low-level method has been added to `RowBuilder` -- `with-column-value` -- that is assumed to just do the "assoc" or "conj" equivalent, and is now used from most implementations of `with-column`; it is explicitly used by the new `next.jdbc.result-set/builder-adapter` and the existing `as-*-adapter` functions have been rewritten in terms of that.

**Comment by seancorfield** [comment]
Do you care about this or should I close it?

**Comment by seancorfield** [comment]
Closing due to lack of feedback/interest.

**Comment by janosmeszaros** [comment]
@seancorfield I created a [PR](https://github.com/metosin/porsas/pull/13) to update `RowBuilder`, could you take a look whether I understood the required changes correctly?

**Comment by seancorfield** [comment]
I can't really speak to any of the internals of the `porsas` stuff but, semantically, the additions look correct.

**Comment by janosmeszaros** [comment]
Thanks for checking
